name: My-GitHubActions-Basics

on: 
  push:
      branches:
      - main
jobs:
  my_testing: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: 
          echo Add other actions to build
          echo test, and deploy your project.
  
  my_deploy:
      runs-on: ubuntu-22.04
      steps:
        - name: Print Text
          run: echo Pisi-Kaki;
